on:
  schedule:
     - cron: '1 1 1 1 *' #At 01:01 on day-of-month 1 in January
  workflow_dispatch:

name: Update test election 2024 data

jobs:
  render:
    name: Get test data
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Packages cache
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-
      - name: Rerun test data
        run: Rscript scripts/TEST_2024-live-data_TEST.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Test data updated' || echo "No changes"
          git push origin || echo "No changes to commit"
